- hosts: localhost
  vars_files:
      - defaults/main.yml
  pre_tasks:
      - name: Update Apt
        become: true
        apt:
            force_apt_get: true
            update_cache: true
            state: present
            cache_valid_time: 86400 # 1 day
        tags: &tags ["install", "core", "productivity-tools"]
  tasks:
      - import_tasks: tasks/git.yml
      - import_tasks: tasks/ssh.yml
      - import_tasks: tasks/core.yml
      - import_tasks: tasks/node.yml
      - import_tasks: tasks/npm-packages.yml
      - import_tasks: tasks/java.yml
      - import_tasks: tasks/fzf.yml
      - import_tasks: tasks/zsh.yml
      - import_tasks: tasks/personal-projects.yml
      - import_tasks: tasks/work.yml
      - import_tasks: tasks/nvim.yml
      - import_tasks: tasks/nvim-wsl.yml
        when: is_wsl == true
      - import_tasks: tasks/nvim-packages.yml
      - import_tasks: tasks/fonts.yml
      - import_tasks: tasks/brave.yml
        when: is_wsl == false
      - import_tasks: tasks/dotfiles.yml
      # - import_tasks: tasks/nvim-setup.yml
      - import_tasks: tasks/productivity-tools.yml
        when: is_wsl == false
      - import_tasks: tasks/background-images.yml
        when: is_wsl == false
