---
- name: Local tasks
  hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
        cache_valid_time: 86400 # 1 day
      tags: [install, core, productivity-tools]
  tasks:
    - name: Import git task
      ansible.builtin.import_tasks: tasks/git.yml

    - name: Import ssh task
      ansible.builtin.import_tasks: tasks/ssh.yml

    - name: Import core task
      ansible.builtin.import_tasks: tasks/core.yml

    - name: Import node task
      ansible.builtin.import_tasks: tasks/node.yml

    - name: Import npm-packages task
      ansible.builtin.import_tasks: tasks/npm-packages.yml

    - name: Import java task
      ansible.builtin.import_tasks: tasks/java.yml

    - name: Import fzf task
      ansible.builtin.import_tasks: tasks/fzf.yml

    - name: Import zsh task
      ansible.builtin.import_tasks: tasks/zsh.yml

    - name: Import personal-projects task
      ansible.builtin.import_tasks: tasks/personal-projects.yml

    - name: Import work task
      ansible.builtin.import_tasks: tasks/work.yml

    - name: Import nvim task
      ansible.builtin.import_tasks: tasks/nvim.yml

    - name: Import nvim-wsl task
      ansible.builtin.import_tasks: tasks/nvim-wsl.yml
      when: is_wsl

    - name: Import fonts task
      ansible.builtin.import_tasks: tasks/fonts.yml

    - name: Import brave task
      ansible.builtin.import_tasks: tasks/brave.yml
      when: not is_wsl

    - name: Import dotfiles task
      ansible.builtin.import_tasks: tasks/dotfiles.yml

    - name: Import productivity-tools task
      ansible.builtin.import_tasks: tasks/productivity-tools.yml
      when: not is_wsl

    - name: Import background-images task
      ansible.builtin.import_tasks: tasks/background-images.yml
      when: not is_wsl
