#!/usr/bin/env zsh

# # or wherever you bash history file lives
# HISTFILE=~/.zsh_history
# # enable history
# set -o history
HISTSIZE=999999999
fc -R ~/.zsh_history

SUDO_APT_INSTALL="sudo apt install"

packages=()

# iterate through all the commands that contain 'sudo apt install '
while IFS=' ' read -A cmd_array; do

    # check if the command starts with 'sudo apt install'
    sudo="${cmd_array[2]}"
    apt="${cmd_array[3]}"
    install="${cmd_array[4]}"
    if [ "$sudo $apt $install" != "$SUDO_APT_INSTALL" ]; then
        continue
    fi

    # append all packages
    for package in "${cmd_array[@]:4}"
    do
        packages+=($package)
    done
done < <(history 0 | grep 'sudo apt install ')

sorted_unique_packages=($(echo "${packages[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

packages_should_be_added=()

# check if packages already exist in ansible tasks
for package in "${sorted_unique_packages[@]}"
do
    check_if_package_exists_command="cat tasks/* | grep -c '${package}'"
    count=$(eval $check_if_package_exists_command)

    if [ $count -ne 0 ]; then
        continue
    fi

    packages_should_be_added+=($package)
done

if [ ${#packages_should_be_added[@]} -eq 0 ]; then
    echo "There are not packages to be added"
    exit 0
fi

echo "These are the packages that should be added: "

for package in "${packages_should_be_added[@]}"
do
    echo -e "- $package"
done

vared -p 'Do you want to create an ansible task for these packages? [Y/n] ' -c response
response=${response:l} #tolower
if [[ $response =~ ^(YES|Y|yes|y| ) ]] || [[ -z $response ]]; then
    # build name string
    name_string="${packages_should_be_added[@]:0:1}"
    for package in "${packages_should_be_added[@]:1}"
    do
        name_string+=", ${package}"
    done
    # build apt string
    apt_string="\"${packages_should_be_added[@]:0:1}\""
    for package in "${packages_should_be_added[@]:1}"
    do
        apt_string+=", \"$package\""
    done

    # create file and write to it
    touch tasks/new-packages.yml
    echo "- name: Install System New Packages ($name_string)" > tasks/new-packages.yml
    echo "  become: true" >> tasks/new-packages.yml
    echo "  apt:" >> tasks/new-packages.yml
    echo "      name: [$apt_string]" >> tasks/new-packages.yml
    echo '  tags: &tags ["new-packages"]' >> tasks/new-packages.yml
fi
