---
- name: Install fzf
  become: true
  ansible.builtin.apt:
    name: [fzf]
  tags: &tags [install, fzf]

- name: Create bin directory
  ansible.builtin.file:
    path: "{{ bin_dir_path }}"
    state: directory
    mode: "0644"
  tags: *tags

- name: Install fd
  become: true
  ansible.builtin.apt:
    name: [fd-find]
  tags: *tags

- name: Check that the fd exists
  ansible.builtin.stat:
    path: "{{ bin_dir_path }}/fd"
  register: fd_exists
  tags: *tags

- name: Remove the fd folder
  ansible.builtin.file:
    path: "{{ bin_dir_path }}/fd"
    state: absent
  when: fd_exists.stat.isdir is defined and fd_exists.stat.isdir
  tags: *tags

- name: Link fd
  ansible.builtin.file:
    path: "{{ bin_dir_path }}/fd"
    src: /usr/bin/fdfind
    state: link
    force: true
  tags: *tags

# Alternative until bat 0.21.0 is available
# I need this version of bat, otherwise it crushes with the ripgrep installation
- name: Download bat
  become: true
  ansible.builtin.get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.21.0/bat_0.21.0_amd64.deb
    dest: ~/.bat-installer
    mode: a+x
  tags: *tags

- name: Install bat
  become: true
  ansible.builtin.shell: dpkg -i ~/.bat-installer && rm -rf ~/.bat-installer
  changed_when: false
  tags: *tags
# - name: Install bat
#   become: true
#   apt:
#     name: ["bat"]
#   tags: *tags

# - name: Check that the bat exists
#   stat:
#       path: "{{ bin_dir_path }}/bat"
#   register: bat_exists
#   tags: *tags

# - name: Remove the bat folder
#   file:
#     path: "{{ bin_dir_path }}/bat"
#     state: absent
#   when: bat_exists.stat.isdir is defined and bat_exists.stat.isdir
#   tags: *tags

# - name: Link bat
#   file:
#     path: "{{ bin_dir_path }}/bat"
#     src: /usr/bin/batcat
#     state: link
#     force: yes
#   tags: *tags
