---
- name: Add neovim-ppa
  become: true
  ansible.builtin.command: add-apt-repository -y ppa:neovim-ppa/unstable
  changed_when: false
  tags: &tags [install, nvim]

- name: Install neovim
  become: true
  ansible.builtin.apt:
    name: [neovim]
  tags: *tags

- name: Install neovim prerequisites(xclip, ripgrep)
  become: true
  ansible.builtin.apt:
    name: [xclip, ripgrep]
  tags: *tags
