---
- name: Check that win32yank.exe exists
  ansible.builtin.stat:
    path: "{{ bin_dir_path }}/win32yank.exe"
  register: win32yank_stats
  tags: &tags [install, nvim, nvim-wsl]

- name: Download win32yank.exe
  ansible.builtin.get_url:
    url: https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
    dest: /tmp/win32yank.zip
    mode: "0755"
  when: not win32yank_stats.stat.exists
  tags: *tags

- name: Unzip win32yank.exe
  ansible.builtin.unarchive:
    src: /tmp/win32yank.zip
    dest: win32yank.exe
    mode: "0755"
  when: not win32yank_stats.stat.exists
  tags: *tags

- name: Setup win32yank.exe
  ansible.builtin.shell: chmod +x /tmp/win32yank.exe && mv /tmp/win32yank.exe {{ bin_dir_path }}
  changed_when: false
  when: not win32yank_stats.stat.exists
  tags: *tags
