---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    dest: "{{ dest_key | dirname }}"
    state: directory
    mode: "0700"
  tags: &tags [install, ssh]

- name: Install ssh key
  ansible.builtin.copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0600"
  tags: *tags

- name: Install ssh key public
  ansible.builtin.copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: "0644"
  tags: *tags

- name: Set authorized key took from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ home }}/.ssh/id_rsa.pub"
  with_fileglob:
    - "{{ home }}/.ssh/*.pub"
